### ISSUE TITLE
Raw article content should be given as an ArticleModel attribute

### ISSUE THREAD

**Issue by MineRobber9000** [tdwtf/WtfWebApp#179]
I shouldn't have to parse the garbled mess that is `BodyHtml` just to get the text form of the article content. (referring to inane-looking encoded characters within (why are angle brackets encoded like that))

I just want to write a terminal app that allows for easy viewing of TDWTF articles so I can read in the comfort of a server I use. Unfortunately, due to there being no `BodyRaw` or similar attribute, I'd have to parse the entirety of `BodyHtml` to affect what ultimately turns out to be the removal of tags.

**Comment by BenLubar** [comment]
There is no "raw" version of the article. BodyHtml is what is stored in the database.

Use a JSON parsing library to parse JSON. For example, try going to one of the article API pages in your browser and running this in the developer console: `JSON.parse(document.body.innerText).BodyHtml`

**Comment by MineRobber9000** [comment]
I know how to parse JSON, the fact that you think that's my problem is frankly disconcerting. What I'm saying is that work could be offloaded onto the API instead of forcing people to do it whenever they want to write programs. Making `BodyRaw` is pretty much:

 - Parse away all of the HTML tags
 - Turn the MS Word-encoded and HTML-escaped characters into raw text form (<MS Word ellipse> -> "...", etc.)

**Comment by RemyPorter** [comment]
Okay, a few things, first off- there are no "MS Word Encoded" characters- everything is Unicode. "…" and "..." are totally different- the former is a character, the latter is three characters. If that's a problem for your client… make sure your client is built to handle unicode strings. It's 2018, there's no excuse for NOT doing that.

Second: from the editorial side, there is no non-HTML-containing version of the article. For a variety of reasons, articles are uploaded to the site in HTML. So, as you say, we'd need to generate the "raw" version programatically.

Third: 90% of the tags we use are pretty common: p, blockquote, em, strong, pre and code are the main ones. So yes, those would be easy to just remove when necessary. It's the edge cases that kill you, though. How should the API render a table? Images? The rare interactive script? Even blockquotes probably need special formatting, just so they stand out.

The data, in the database, is stored as HTML snippets, usually containing a subset of common HTML tags. There's no one "right way" to render HTML in a terminal-friendly format. That operation SHOULD be left to the clients. Tags, as used in article bodies, are generally semantic in nature, and stripping them out, in many cases, would alter the interpretation of the article.

I'm not convinced the API should be taking control of the presentation of articles in the way you suggest- and that *is* what you're suggesting. We can have a debate about whether or not HTML is the right format to store articles in (but changing that would require a VERY compelling case), but given that it *is* what format the articles are stored in, the whole point is to give clients control over presentation. Calling it "removal of tags" is really understating the problem- you're not removing tags, you're converting \<p\> tags to line-breaks, \<img\>s to probably some rendering of `alt` text, etc.

//We use an HTML-based workflow for a number of reasons, some just legacy (it's how it used to work since forever ago) and some in terms of "our writers can all produce HTML, and this gives them control of article structure as needed".
//The site actually looks pretty good in Lynx, so the HTML in use renders nicely in plaintext
