### ISSUE TITLE
Feature: Add HSTS preload, redirect http to https

### ISSUE THREAD

**Issue by djechelon** [tdwtf/WtfWebApp#195]
Hi, in the era of "let's everyone encrypt" I saw that http://thedailywtf.com is still accessible, nor it redirects to the secure version.

It would be adivsable to add https-only. And, personally, I prefer to add every site globally to the preload list (which indeed makes the browsers fatter... until we all switch to https)

Further reading: https://hstspreload.org/?domain=thedailywtf.com

**Comment by apxltd** [comment]
I switched to using cloudflare several months back, and no real issues that I could tell. Today , I just checked this off...

![image](https://user-images.githubusercontent.com/3965467/133765148-1c25a605-1871-4261-95f0-9857a17dfc92.png)

There's a HSTS preload setting, but it has some switches that I don't know. Including `no-sniff`, which may be good, or bad.

![image](https://user-images.githubusercontent.com/3965467/133765326-dec3f7bc-519a-4db3-82b0-5ef27d812bd4.png)


I suppose "always HTTPS" is ok enough? I do'nt get HSTS otherwise.

**Comment by djechelon** [comment]
No-sniff is a header used for downloads

It basically tells some browser _if you are downloading a file .jpeg that contains Windows executable content, don't fu**in offer the user to launch the file_.

It is considered a security header because it prevents a hacked site to serve bad content over innocent content-types

**Comment by djechelon** [comment]
Also, before I forget. The preload function works as this. You enable all the options (no-sniff is optional), then subscribe to hstspreload.org. Future releases of major browser will contain your domain hard coded into a list of https-only domains.

That's all.

Cheers

**Comment by apxltd** [comment]
Ah ha, thanks for the explanation :)

OK I'll consider enabling after no one complaihs about HTTPS only :D
